# Generated by Django 5.1.4 on 2025-01-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=80)),
                ('type', models.CharField(choices=[('IN', 'Ingreso'), ('EG', 'Egreso')], default='IN', max_length=2)),
                ('transfer', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Concept',
                'verbose_name_plural': 'Concepts',
                'db_table': 'concepts',
            },
        ),
    ]
