# Generated by Django 5.1.4 on 2025-01-10 12:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
