# Generated by Django 5.1.4 on 2025-01-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move', '0003_alter_move_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='date',
            field=models.DateField(),
        ),
    ]
