# Generated by Django 5.1.4 on 2025-01-16 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move', '0004_alter_move_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='date',
            field=models.DateField(default=datetime.date(2025, 1, 16)),
        ),
    ]
